name: mlops-kickoff-2
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - matplotlib
  - seaborn
  - shap
  - lime
  - jupyter
  - ipykernel
  - pytest
  - pytest-cov
  - pip
  - pyyaml

  - pip:
    - fastapi
    - uvicorn[standard]
    - wandb
